fix vale

diff --git a/script/vale b/script/vale
--- a/script/vale
+++ b/script/vale
@@ -1,3 +1,7 @@
 #!/bin/sh
 
-vale ./*.md _posts/*.md _resume_positions/*.md --minAlertLevel=error
+if ! [ -x "$(command -v vale)" ]; then
+  echo "Vale not found. Skippintg."
+else 
+  vale ./*.md _posts/*.md _resume_positions/*.md --minAlertLevel=error
+fi
